package evaluator

// Special operators introduced by the evaluator
type Listify struct{}  // Convert a set of values to a list (generated by {...})
type Indexify struct{} // Convert a value to a list index (generated by [..]
